spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/Telemetry
    username: postgres
    password: postgres

    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true